[build]
  publish = "web-admin"
  functions = "web-admin/functions"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/tv"
  to = "/tv.html"
  status = 200

[[redirects]]
  from = "/tv/"
  to = "/tv.html"
  status = 200

[[redirects]]
  from = "/api/catalog"
  to = "/.netlify/functions/catalog"
  status = 200

[[redirects]]
  from = "/api/youtube-info"
  to = "/.netlify/functions/youtube-info"
  status = 200
